feat: Remove `requirements.txt` for `pyproject.toml`
mihaelaaleks/playlist_curator pull request #22
Opened 2024-04-07 17:40 UTC by LeoFrancoCrespo

This PR also does the following:
- Updates the `README.md` to reference the new environment setup document. 
- Updates the action file to use the toml file to install the dependencies instead of requirements.txt

2024-04-18 13:36 UTC, mihaelaaleks requested changes
Solid change! Everything runs perfectly fine, also with the notebooks. I like the separation of a development environment too.

2024-04-18 13:36 UTC, mihaelaaleks commented on pyproject.toml
> +]
Was missing only one dependency when I ran it: 

>  "Flask-WTF==1.2.1"

2024-04-18 13:36 UTC, mihaelaaleks commented on pyproject.toml
> +]
Is this expected during pip install of [dev]:  
![image](https://github.com/mihaelaaleks/playlist_curator/assets/74715450/d61f024b-8815-48f3-825c-9afeee631125)

2024-04-18 13:36 UTC, mihaelaaleks commented on README.md
I've updated the readme format after this PR came in, I'll include this when resolving the merge conflict

2024-04-18 13:36 UTC, mihaelaaleks commented on .gitignore
>  # VSCode
These probably should also be added to the gitignore right?
![image](https://github.com/mihaelaaleks/playlist_curator/assets/74715450/01b4917d-458d-4783-9014-aefea73b8408)

2024-04-19 09:18 UTC, LeoFrancoCrespo commented on pyproject.toml
> +]
Added

2024-04-19 09:18 UTC, LeoFrancoCrespo commented on pyproject.toml
> +]
Yes it is expected

2024-04-19 09:28 UTC, LeoFrancoCrespo commented on README.md
i've merged and resolved the conflics ty

2024-04-19 09:28 UTC, LeoFrancoCrespo commented on .gitignore
>  # VSCode
They are added to the gitignore

When you run the pip install locally from pyproject toml they get created as part of that install :)

2024-04-19 09:54 UTC, mihaelaaleks commented on pyproject.toml
> +dependencies = [
546

2024-04-19 10:02 UTC, merged